-- 新闻
CREATE TABLE IF NOT EXISTS `xinwen`(
   `id` INT UNSIGNED AUTO_INCREMENT,
   `docid` VARCHAR(255) NOT NULL,
   `title` VARCHAR(255) NOT NULL,
   `url` VARCHAR(255) NOT NULL,
   `imgsrc` VARCHAR(255) NOT NULL,
   `imgsrcis` VARCHAR(255) NOT NULL,
   `imgsrcs` VARCHAR(255) NOT NULL,
   `typesrc` VARCHAR(255) NOT NULL,
   `source` VARCHAR(255) DEFAULT '',
   `ptime` DATETIME NOT NULL,
   `body` TEXT NOT NULL,
   `videourl` VARCHAR(255) DEFAULT '',
   PRIMARY KEY ( `id` ),
   UNIQUE INDEX (`docid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

 CREATE TABLE tors(
   Id INTEGER PRIMARY KEY AUTOINCREMENT, 
   Sid VARCHAR(255) UNIQUE NOT NULL,
   Title VARCHAR(255) NOT NULL,
   Browse VARCHAR(255) NOT NULL,
   Photo VARCHAR(255) NOT NULL,
   Type VARCHAR(255) NOT NULL,
   Url VARCHAR(255) NOT NULL,
   Source VARCHAR(255) NOT NULL,
   Time DATE NOT NULL,
   Introduction TEXT NOT NULL,
   Image1 VARCHAR(255),
   Image2 VARCHAR(255),
   Image3 VARCHAR(255),
   Isimage INT NOT NULL,
   Content TEXT ,
   Video VARCHAR(255)
);

